[package]
name = "domain"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"], default-features = false }
utoipa = { version = "5.3", optional = true }

[features]
default = []
openapi = ["utoipa"]
